//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by formation.rc
//
#define IDS_NAME                        2
#define IDS_FORCECLR                    4
#define IDS_DSPLYFRC                    5
#define IDS_PARAMETERS                  8
#define IDS_LIBDESC                     9
#define IDD_PATHFOLLOW                  101
#define IDD_FORMATION                   101
#define IDC_NOPICKCURSOR                103
#define IDB_PICKNODE                    105
#define IDB_MASK_PICKNODE               106
#define IDS_PFGOODPICK                  150
#define IDS_SFGOODPICK                  150
#define IDS_PATHFOLLOW_CLASSNAME        151
#define IDS_SURFACEARRIVE_CLASSNAME     151
#define IDS_FORMATION_CLASSNAME         151
#define IDS_PFBADPICK                   152
#define IDS_SFBADPICK                   152
#define IDS_PFRADIUS                    153
#define IDS_PFAWARE                     154
#define IDS_PFLOOP                      155
#define IDS_PFSTART                     156
#define IDS_PFAWAREDEVIATION            157
#define IDS_PFSEED                      158
#define IDS_PFREVERSE                   160
#define IDS_WHOM                        161
#define IDS_SURFACES                    161
#define IDS_OBJECTS                     161
#define IDS_SHAPEPROMPT                 162
#define IDS_EMPTY                       163
#define IDS_SFDISTANCE                  165
#define IDS_SFTWOSIDED                  166
#define IDS_PICKPROMPT                  167
#define IDS_MULTSEL                     168
#define IDS_TARGETCLR                   169
#define IDS_DSPLYTARGET                 170
#define IDS_DISPLAYTARGET               170
#define IDS_TARGETSCL                   171
#define IDS_USEPROJECTION               172
#define IDS_RANDOM_CLOSEST              172
#define IDS_XVECTOR                     173
#define IDS_CLOSEST                     173
#define IDS_YVECTOR                     174
#define IDS_EVERYFRAME                  174
#define IDS_ZVECTOR                     175
#define IDS_SPEED                       175
#define IDS_DISTANCE                    176
#define IDS_RATE                        177
#define IDS_FACING                      178
#define IDS_SEED                        179
#define IDS_HEIGHT                      180
#define IDS_DESCENTSTART                181
#define IDS_RATEDEVIATION               182
#define IDS_SPEEDDEVIATION              183
#define IDS_DISTANCEDEVIATION           184
#define IDS_HEIGHTDEVIATION             185
#define IDS_DESCENTSTARTDEVIATION       186
#define IDS_DISABLEAFTERARRIVING        187
#define IDS_OFFSET                      188
#define IDS_USE_NORMAL                  189
#define IDS_NORMALX                     190
#define IDS_NORMALY                     191
#define IDS_NORMALZ                     192
#define IDS_UN_WHOM                     193
#define IDS_SELECT                      194
#define IDS_NONE                        195
#define IDS_MULTIPLE                    196
#define IDS_DISPLAYOFFSET               197
#define IDS_FORMATION_NAME              198
#define IDS_MATRICES                    199
#define IDS_DISPLAYFORMATION            200
#define IDS_DISPLAYSCALE                201
#define IDS_RADIUS                      202
#define IDC_RANDOM                      1000
#define IDC_CLOSEST                     1001
#define IDC_NAMESEL                     1003
#define IDC_PICKNODE                    1004
#define IDC_EVERYFRAME                  1005
#define IDC_FACING                      1006
#define IDC_DISABLEAFTERARRIVING        1007
#define IDC_USE_NORMAL                  1008
#define IDC_DISPLAYOFFSET               1009
#define IDC_SETFORMATION                1009
#define IDC_PICKLEADER                  1010
#define IDC_PFAWARE                     1021
#define IDC_PFAWARESPIN                 1022
#define IDC_PFRADIUS                    1023
#define IDC_SFDISTANCE                  1023
#define IDC_PFRADIUSSPIN                1024
#define IDC_SFDISTANCESPIN              1024
#define IDC_RADIUS                      1024
#define IDC_PFAWAREDEVIATION            1025
#define IDC_RADIUSSPIN                  1025
#define IDC_PFAWAREDEVIATIONSPIN        1026
#define IDC_DISPLAYSCALE                1026
#define IDC_DISPLAYSCALESPIN            1027
#define IDC_FORCEDSPLY                  1030
#define IDC_FORCECLR                    1031
#define IDC_PFLOOP                      1032
#define IDC_SFTWOSIDED                  1032
#define IDC_PFSTART                     1033
#define IDC_PFREVERSE                   1034
#define IDC_TARGETDSPLY                 1035
#define IDC_TARGETCLR                   1036
#define IDC_USEPROJECTION               1037
#define IDC_DISPLAYFORMATION            1037
#define IDC_PFSEED                      1102
#define IDC_PFSEEDSPIN                  1103
#define IDC_TARGSCALE                   1104
#define IDC_TARGSCALESPIN               1105
#define IDC_XVECTOR                     1106
#define IDC_XVECTORSPIN                 1107
#define IDC_YVECTOR                     1108
#define IDC_YVECTORSPIN                 1109
#define IDC_ZVECTOR                     1110
#define IDC_ZVECTORSPIN                 1111
#define IDC_SPEED                       1114
#define IDC_SPEEDSPIN                   1115
#define IDC_DISTANCE                    1116
#define IDC_DISTANCESPIN                1117
#define IDC_SEED                        1118
#define IDC_SEEDSPIN                    1119
#define IDC_RATE                        1120
#define IDC_RATESPIN                    1121
#define IDC_OFFSET                      1122
#define IDC_OFFSETSPIN                  1123
#define IDC_HEIGHT                      1126
#define IDC_HEIGHTSPIN                  1127
#define IDC_DESCENTSTART                1128
#define IDC_DESCENTSTARTSPIN            1129
#define IDC_HEIGHTDEVIATION             1130
#define IDC_HEIGHTDEVIATIONSPIN         1131
#define IDC_DESCENTSTARTDEVIATION       1132
#define IDC_DESCENTSTARTDEVIATIONSPIN   1133
#define IDC_RATEDEVIATION               1134
#define IDC_RATEDEVIATIONSPIN           1135
#define IDC_SPEEDDEVIATION              1136
#define IDC_SPEEDDEVIATIONSPIN          1137
#define IDC_DISTANCEDEVIATION           1138
#define IDC_DISTANCEDEVIATIONSPIN       1139
#define IDC_NORMALX                     1140
#define IDC_NORMALXSPIN                 1141
#define IDC_NORMALY                     1146
#define IDC_NORMALYSPIN                 1147
#define IDC_NORMALZ                     1148
#define IDC_NORMALZSPIN                 1149

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
