g++ -c -O3 -mcpu=pentiumpro -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-mem -fforce-addr -m32 -fPIC -pthread -std=c++98 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DHYPERTHREAD -DNV_CG -D__NO_CTYPE -I.  -I/usr/X11R6/include dgsutil.cpp
g++ -c -O3 -mcpu=pentiumpro -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-mem -fforce-addr -m32 -fPIC -pthread -std=c++98 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DHYPERTHREAD -DNV_CG -D__NO_CTYPE -I.  -I/usr/X11R6/include dgsshade.cpp
g++ -c -O3 -mcpu=pentiumpro -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-mem -fforce-addr -m32 -fPIC -pthread -std=c++98 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DHYPERTHREAD -DNV_CG -D__NO_CTYPE -I.  -I/usr/X11R6/include dielecshade.cpp
g++ -c -O3 -mcpu=pentiumpro -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-mem -fforce-addr -m32 -fPIC -pthread -std=c++98 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DHYPERTHREAD -DNV_CG -D__NO_CTYPE -I.  -I/usr/X11R6/include partishade.cpp
g++ -c -O3 -mcpu=pentiumpro -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-mem -fforce-addr -m32 -fPIC -pthread -std=c++98 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DHYPERTHREAD -DNV_CG -D__NO_CTYPE -I.  -I/usr/X11R6/include pathshade.cpp
g++ -c -O3 -mcpu=pentiumpro -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-mem -fforce-addr -m32 -fPIC -pthread -std=c++98 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DHYPERTHREAD -DNV_CG -D__NO_CTYPE -I.  -I/usr/X11R6/include physlight.cpp
g++ -c -O3 -mcpu=pentiumpro -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-mem -fforce-addr -m32 -fPIC -pthread -std=c++98 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DHYPERTHREAD -DNV_CG -D__NO_CTYPE -I.  -I/usr/X11R6/include physlens.cpp
g++ -shared -export-dynamic -static-libgcc -Wl,-Bsymbolic,--whole-archive,--allow-shlib-undefined -o physics.so dgsutil.o dgsshade.o dielecshade.o partishade.o pathshade.o physlight.o physlens.o -Wl,--no-whole-archive

