i686-pc-linux-gnu-g++-4.0.2 -c -O3 -mtune=pentiumpro -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-addr -Wall -Wno-non-virtual-dtor -fPIC -std=c++98 -pthread -m32 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DHYPERTHREAD -DNV_CG -D__NO_CTYPE -I.  -I/usr/X11R6/include dgsutil.cpp
i686-pc-linux-gnu-g++-4.0.2 -c -O3 -mtune=pentiumpro -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-addr -Wall -Wno-non-virtual-dtor -fPIC -std=c++98 -pthread -m32 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DHYPERTHREAD -DNV_CG -D__NO_CTYPE -I.  -I/usr/X11R6/include dgsshade.cpp
i686-pc-linux-gnu-g++-4.0.2 -c -O3 -mtune=pentiumpro -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-addr -Wall -Wno-non-virtual-dtor -fPIC -std=c++98 -pthread -m32 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DHYPERTHREAD -DNV_CG -D__NO_CTYPE -I.  -I/usr/X11R6/include dielecshade.cpp
i686-pc-linux-gnu-g++-4.0.2 -c -O3 -mtune=pentiumpro -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-addr -Wall -Wno-non-virtual-dtor -fPIC -std=c++98 -pthread -m32 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DHYPERTHREAD -DNV_CG -D__NO_CTYPE -I.  -I/usr/X11R6/include partishade.cpp
i686-pc-linux-gnu-g++-4.0.2 -c -O3 -mtune=pentiumpro -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-addr -Wall -Wno-non-virtual-dtor -fPIC -std=c++98 -pthread -m32 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DHYPERTHREAD -DNV_CG -D__NO_CTYPE -I.  -I/usr/X11R6/include pathshade.cpp
i686-pc-linux-gnu-g++-4.0.2 -c -O3 -mtune=pentiumpro -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-addr -Wall -Wno-non-virtual-dtor -fPIC -std=c++98 -pthread -m32 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DHYPERTHREAD -DNV_CG -D__NO_CTYPE -I.  -I/usr/X11R6/include physlight.cpp
i686-pc-linux-gnu-g++-4.0.2 -c -O3 -mtune=pentiumpro -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-addr -Wall -Wno-non-virtual-dtor -fPIC -std=c++98 -pthread -m32 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DHYPERTHREAD -DNV_CG -D__NO_CTYPE -I.  -I/usr/X11R6/include physlens.cpp
i686-pc-linux-gnu-g++-4.0.2 -shared -export-dynamic -static-libgcc -Wl,-Bsymbolic,--whole-archive,--allow-shlib-undefined -o physics.so dgsutil.o dgsshade.o dielecshade.o partishade.o pathshade.o physlight.o physlens.o -Wl,--no-whole-archive

