g++ -c -O3 -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -fforce-addr -frerun-cse-after-loop -fstrength-reduce -fforce-mem -pthread -ansi -fPIC -m64 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DBIT64 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DSSE_INTRINSICS -DNV_CG -D__NO_CTYPE -DHYPERTHREAD -I.  -I/usr/X11R6/include dgsutil.cpp
g++ -c -O3 -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -fforce-addr -frerun-cse-after-loop -fstrength-reduce -fforce-mem -pthread -ansi -fPIC -m64 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DBIT64 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DSSE_INTRINSICS -DNV_CG -D__NO_CTYPE -DHYPERTHREAD -I.  -I/usr/X11R6/include dgsshade.cpp
g++ -c -O3 -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -fforce-addr -frerun-cse-after-loop -fstrength-reduce -fforce-mem -pthread -ansi -fPIC -m64 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DBIT64 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DSSE_INTRINSICS -DNV_CG -D__NO_CTYPE -DHYPERTHREAD -I.  -I/usr/X11R6/include dielecshade.cpp
g++ -c -O3 -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -fforce-addr -frerun-cse-after-loop -fstrength-reduce -fforce-mem -pthread -ansi -fPIC -m64 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DBIT64 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DSSE_INTRINSICS -DNV_CG -D__NO_CTYPE -DHYPERTHREAD -I.  -I/usr/X11R6/include partishade.cpp
g++ -c -O3 -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -fforce-addr -frerun-cse-after-loop -fstrength-reduce -fforce-mem -pthread -ansi -fPIC -m64 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DBIT64 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DSSE_INTRINSICS -DNV_CG -D__NO_CTYPE -DHYPERTHREAD -I.  -I/usr/X11R6/include pathshade.cpp
g++ -c -O3 -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -fforce-addr -frerun-cse-after-loop -fstrength-reduce -fforce-mem -pthread -ansi -fPIC -m64 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DBIT64 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DSSE_INTRINSICS -DNV_CG -D__NO_CTYPE -DHYPERTHREAD -I.  -I/usr/X11R6/include physlight.cpp
g++ -c -O3 -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -fforce-addr -frerun-cse-after-loop -fstrength-reduce -fforce-mem -pthread -ansi -fPIC -m64 -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DBIT64 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DSSE_INTRINSICS -DNV_CG -D__NO_CTYPE -DHYPERTHREAD -I.  -I/usr/X11R6/include physlens.cpp
g++ -shared -export-dynamic -Wl,--whole-archive -Bsymbolic -m64 -o physics.so dgsutil.o dgsshade.o dielecshade.o partishade.o pathshade.o physlight.o physlens.o -Wl,--no-whole-archive

