g++-4.0.0 -c -O3 -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-addr -Wall -ansi -fPIC -pthread -m64 -Wno-non-virtual-dtor -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DBIT64 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DSSE_INTRINSICS -DNV_CG -D__NO_CTYPE -DHYPERTHREAD -I/usr/X11R6/include -I.  dgsutil.cpp
g++-4.0.0 -c -O3 -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-addr -Wall -ansi -fPIC -pthread -m64 -Wno-non-virtual-dtor -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DBIT64 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DSSE_INTRINSICS -DNV_CG -D__NO_CTYPE -DHYPERTHREAD -I/usr/X11R6/include -I.  dgsshade.cpp
g++-4.0.0 -c -O3 -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-addr -Wall -ansi -fPIC -pthread -m64 -Wno-non-virtual-dtor -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DBIT64 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DSSE_INTRINSICS -DNV_CG -D__NO_CTYPE -DHYPERTHREAD -I/usr/X11R6/include -I.  dielecshade.cpp
g++-4.0.0 -c -O3 -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-addr -Wall -ansi -fPIC -pthread -m64 -Wno-non-virtual-dtor -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DBIT64 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DSSE_INTRINSICS -DNV_CG -D__NO_CTYPE -DHYPERTHREAD -I/usr/X11R6/include -I.  partishade.cpp
g++-4.0.0 -c -O3 -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-addr -Wall -ansi -fPIC -pthread -m64 -Wno-non-virtual-dtor -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DBIT64 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DSSE_INTRINSICS -DNV_CG -D__NO_CTYPE -DHYPERTHREAD -I/usr/X11R6/include -I.  pathshade.cpp
g++-4.0.0 -c -O3 -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-addr -Wall -ansi -fPIC -pthread -m64 -Wno-non-virtual-dtor -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DBIT64 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DSSE_INTRINSICS -DNV_CG -D__NO_CTYPE -DHYPERTHREAD -I/usr/X11R6/include -I.  physlight.cpp
g++-4.0.0 -c -O3 -fexpensive-optimizations -finline-functions -funroll-loops -fomit-frame-pointer -frerun-cse-after-loop -fstrength-reduce -fforce-addr -Wall -ansi -fPIC -pthread -m64 -Wno-non-virtual-dtor -DQMC -DMI_MODULE= -DMI_PRODUCT_RAY -DLINUX -DLINUX_X86 -DX86 -DBIT64 -DEVIL_ENDIAN -D_GNU_SOURCE -D_REENTRANT -DSYSV -DSVR4 -Dinline=__inline__ -DSSE_INTRINSICS -DNV_CG -D__NO_CTYPE -DHYPERTHREAD -I/usr/X11R6/include -I.  physlens.cpp
g++-4.0.0 -shared -export-dynamic --whole-archive -Bsymbolic -m64 -o physics.so dgsutil.o dgsshade.o dielecshade.o partishade.o pathshade.o physlight.o physlens.o -Wl,--no-whole-archive

