//-
// ==========================================================================
// Copyright (C) 2005 ATI Technologies Inc. All rights reserved.
//
// Copyright (C) 1995 - 2006 Autodesk, Inc. and/or its licensors.  All 
// rights reserved.
//
// The coded instructions, statements, computer programs, and/or related 
// material (collectively the "Data") in these files contain unpublished 
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its 
// licensors, which is protected by U.S. and Canadian federal copyright 
// law and by international treaties.
//
// The Data is provided for use exclusively by You. You have the right 
// to use, modify, and incorporate this Data into other products for 
// purposes authorized by the Autodesk software license agreement, 
// without fee.
//
// The copyright notices in the Software and this entire statement, 
// including the above license grant, this restriction and the 
// following disclaimer, must be included in all copies of the 
// Software, in whole or in part, and all derivative works of 
// the Software, unless such copies or derivative works are solely 
// in the form of machine-executable object code generated by a 
// source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. 
// AUTODESK DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED 
// WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF 
// NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR 
// PURPOSE, OR ARISING FROM A COURSE OF DEALING, USAGE, OR 
// TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS LICENSORS 
// BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL, 
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK 
// AND/OR ITS LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY 
// OR PROBABILITY OF SUCH DAMAGES.
//
// ==========================================================================
//+

#include <maya/MFnPlugin.h>
#include <maya/MIOStream.h>
#include <maya/MSceneMessage.h>
#include <maya/MGlobal.h>

//nodes that need to be registered
#include "GLSLShaderNode.h"
#include "fxManagerCmd.h"
//#include "fxVector.h"

//shader interface for configuration parameters
#include "Shader.h"

#include <stdlib.h>

#include <maya/MHWShaderSwatchGenerator.h>
#include <maya/MHardwareRenderer.h>
#include <maya/MGeometryData.h>
#include <maya/MImage.h>

//
// static variables for holding the callback IDs
//
MCallbackId openCallback;
MCallbackId importCallback;
MCallbackId referenceCallback;

MStatus initializePlugin( MObject obj )
//
//	Description:
//		this method is called when the plug-in is loaded into Maya.  It 
//		registers all of the services that this plug-in provides with 
//		Maya.
//
//	Arguments:
//		obj - a handle to the plug-in object (use MFnPlugin to access it)
//
{ 
	MStatus   status;
    const char *sm3;

    if ( NULL != (sm3 = getenv("ASHLI_SM3_SUPPORT"))) {
      if (strcmp( sm3, "0") != 0)
        shader::sSupportSM3 = true;
    }

	const MString& swatchName =	MHWShaderSwatchGenerator::initialize();

    MString swatchClassification;

	// Allow an environment variable to override usage of swatch
	// rendering.
	const char *ashliEnvVar = getenv("ASHLI_SWATCH_RENDERING");
#ifdef WIN32 
  	if (!ashliEnvVar)
  		swatchClassification = ":swatch/" + swatchName;
	else
	{
		if ( 0 != strcmp(ashliEnvVar,"0") )
			swatchClassification = ":swatch/" + swatchName;
	}
#else
	if ( ashliEnvVar && ( 0 != strcmp( ashliEnvVar, "0") ) )
	{
		swatchClassification = ":swatch/" + swatchName;
	}
#endif
  
  	const MString UserClassify( "shader/surface/utility/" + swatchClassification );
	MFnPlugin plugin( obj, "ATI", "6.5", "Any");

	//handle info banner

	// Add plug-in feature registration here
	//

    //register the shader node
	CHECK_MSTATUS( plugin.registerNode("AshliShader", glslShaderNode::sId, glslShaderNode::creator, glslShaderNode::initialize,
		MPxNode::kHwShaderNode, &UserClassify));

    //register a helper command for querying shader information
    plugin.registerCommand( "effectManager", fxManagerCmd::creator, fxManagerCmd::mySyntax); 

	//handle scene callback registration (on load, on save, etc)
    openCallback = MSceneMessage::addCallback(MSceneMessage::kAfterOpen, glslShaderNode::rejigShaders);
    importCallback = MSceneMessage::addCallback(MSceneMessage::kAfterImport, glslShaderNode::rejigShaders);
    referenceCallback = MSceneMessage::addCallback(MSceneMessage::kAfterReference, glslShaderNode::rejigShaders);
 
	return status;
}

MStatus uninitializePlugin( MObject obj )
//
//	Description:
//		this method is called when the plug-in is unloaded from Maya. It 
//		deregisters all of the services that it was providing.
//
//	Arguments:
//		obj - a handle to the plug-in object (use MFnPlugin to access it)
//
{
	MStatus   status;
	MFnPlugin plugin( obj );

	//disconnect callbacks

	// Add plug-in feature deregistration here
	//
    MSceneMessage::removeCallback( openCallback);
    MSceneMessage::removeCallback( importCallback);
    MSceneMessage::removeCallback( referenceCallback);

	//deregister the shader node
	CHECK_MSTATUS(plugin.deregisterNode(glslShaderNode::sId));

	//deregister any additional commands

	return status;
}


